---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: spring-boot-sample
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: spring-boot-sample@sha256:c583239ce94f3cc5b8b5cecc140da8bb4129865e538ebac8c49399cf79afdeeb
        namespace: spring-boot-sample
      name: latest
