---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    app: spring-boot-sample
    provider: fabric8
    version: 0.0.1-SNAPSHOT
    group: com.sample.spring
  name: spring-boot-sample
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-sample
    provider: fabric8
    group: com.sample.spring
